### ISSUE TITLE
How to use it in different timezones?

### ISSUE THREAD

**Issue by mikekgr** [G6EJD/ESP-Novelty-Xmas-and-NY-Countdown#1]
Hello Sir,
first of all thanks for your fine idea to build an electronic countdown display !
I am from Greece, that now we have timezome +2. 
I tried to modify your code using Greek timezone but without success. Actually I modified your file ESP8266_XMAS_NY_Countdown_01.ino
 at line 139 your original code is:  configTime(0 * 3600, 0, "pool.ntp.org", "time.nist.gov");   and I changed to:  configTime(2 * 3600, 0, "pool.ntp.org", "time.nist.gov");
The above did not work. The OLED time appeared at the top-left of the OLED is correct but all the calculation seems that is based in timezone 0 and not in my timezone +2.
Can you guide me in order to run your code correct for my timezone?

Thanks and Best Regards,
Mike Kranidis

**Comment by G6EJD** [comment]
OK, for the ESP8266 you are correct:
configTime(2 * 3600, 0, "pool.ntp.org", "time.nist.gov");
Add +2hours to the time.
For your location you need to add 2-hours to the UNIX time which is always in UTC:
https://www.unixtimestamp.com/
Simply subtract 2*3600 from the numbers for Xmas Day and New Years Day, it will happen earlier for you than me in GMT time zone. Or for New Year Day = 1514764799

**Comment by mikekgr** [comment]
Dear Sir,
Thanks a lot. I will try your suggestion and I will let you know.
Best Regards, 
Mike Kranidis 
P. S. Servicing from my memory, it seems that because all the calculations are based on UTC time, even the Day change is performed at 02:00 instead of at 00:00 so this also need adjustment and I am not sure where to change...

**Comment by mikekgr** [comment]
Also I found that for some strange reason, at the top right corner the date stamp says 05.11.2017 instead of the correct: 05.12.2017 How to correct it?
Thanks a lot

**Comment by G6EJD** [comment]
OK, I have fixed all this for you. Now all you need do is change the TZone definition to your region in your case 2, then compile and upload.

The problem with the month and the ESP8266 time library is that it ranges 0-11 rather than the convention of 1-12 used in the ESP32 library! I added 1 to the month to correct that. 

I also reduced the heading by (ccyy 2017) only display the yy element of 2017.

Regarding the day changes, this all works correctly with the ESP32 but unfortunately DST changes on the ESP8266 were never implemented and so does not work.  e.g. configtime(Timezeone,DST,"timeserver) the DST element does nothing! There are some libraries around that solve the DST issue, but they are not easy to use or integrate.

Thank you for finding the anomalies.

**Comment by mikekgr** [comment]
Dear Sir,
thanks a lot for the help offered to me.
Have a nice rest of the day.

Thanks and Best Regards,
Mike Kranidis
